name: VRT_record screenshots

on: workflow_dispatch

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  record_screenshot:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write

    steps:
      - name: Git checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          lfs: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      # Create screenshots
      - name: test
        run: ./gradlew nano-ui:recordRoborazziDebug --tests "RoborazziTest" --stacktrace

      # Upload screenshots to GitHub Actions Artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: app/build/outputs/roborazzi
          retention-days: 30