name: VRT_compare screenshots

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '実行ブランチ'
        required: true
        type: string

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout ${{ github.event.inputs.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          lfs: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      # Download screenshots from main branch
      - uses: dawidd6/action-download-artifact@v8
        with:
          name: screenshots
          workflow: vrt_record_screenshot.yml
          path: nano-ui/build/outputs/roborazzi
          branch: master
          use_unzip: false
          if_no_artifact_found: fail

      # If there is a difference between the screenshots, the test will fail.
      - name: compare test
        id: compare-test
        run: ./gradlew nano-ui:compareRoborazziDebug --tests "RoborazziTest" --stacktrace

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-diff
          path: nano-ui/build/outputs/roborazzi
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-diff-reports
          path: nano-ui/build/reports
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-diff-test-results
          path: nano-ui/build/test-results
          retention-days: 30
